spring:
    profiles:
        active: local
    servlet:
        multipart:
            #单个文件大小
            max-file-size: 1GB
            # 设置总上传的文件大小
            max-request-size: 5GB
    main:
        banner-mode: off
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        view:
            prefix: /WEB-INF/
            suffix: .jsp
        static-path-pattern: /**
    thymeleaf:
        cache: false
        enabled: false
    # redis 集群配置
    redis:
        timeout: 60000ms
        password: rollinrockz
        database: 0
        cluster:
            # 连接池参数
            min-idle: 8
            max-idle: 16
            max-active: 32
            nodes:
                - 124.221.109.245:7002
                - 124.221.109.245:7003
                - 124.221.109.245:7004
            max-redirects: 6

springfox:
    documentation:
        swagger-ui:
            base-url: /
            enabled: true

server:
    port: 80
    servlet:
        context-path: /
        jsp:
            init-parameters:
                development: true
    self-path:
        basedir: D:/home/futureCountry/upload

    tomcat:
        use-relative-redirects: true
        remote-ip-header: X-Real-IP
        protocol-header: X-Forwarded-Proto
