spring:
    #配置数据源信息
    datasource:
        #配置数据源类型
        type: com.zaxxer.hikari.HikariDataSource
        #配置连接数据库的各个信息
        driver-class-name: com.mysql.cj.jdbc.Driver
        #设置字符集
        url: jdbc:mysql://xxxxxx:3306/mall_user?characterEncoding=utf-8&useSSL=false
        username: root
        password: xxxxxxx

    #配置SQL输出语句
    mybatis-plus:
        configuration:
            log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    #配置类型别名所对应的包
    type-aliases-package: com.example.demo

mybatis-plus:
    mapper-locations: classpath:mybatis/*.xml
